---
# For configuration options and examples, please see:
# https://Github.com/benphelps/homepage/wiki/Services

# Infrastructure
- Infrastructure  :
    - Proxmox :
          icon: /icons/catppuccin_icons/proxmox.png
          href: http://pve1.int.jersh.tech:8006
          widget:
            type: proxmox
            url: https://pve1.int.jersh.tech:8006
            username: api@pam!homepage
            password: 706151b5-5682-4d57-929f-24e73c36670c
    - TrueNAS:
          icon: /icons/catppuccin_icons/truenas.png
          href: https://truenas.int.jersh.tech
          widget:
            type: truenas
            url: https://truenas.int.jersh.tech
            key: 1-DSnLyax7ei5luDPkXPp6LBMj1DI7Wh6yb6isI8qVtMOaucqMu5tkRpTwkIonKHZM # not required if using username / password

- Networking:
    - UniFi:
        icon: /icons/catppuccin_icons/ubiquiti.png
        href: https://unifi.int.jersh.tech/network/default/dashboard
    - Pi-Hole: 
        icon: /icons/catppuccin_icons/pihole.png
        href: http://pi-hole.int.jersh.tech/admin
    - Cloudflare Zero Trust:
        icon: /icons/catppuccin_icons/cloudflare.png
        href: https://one.dash.cloudflare.com/e50594c4951fff63354cb386ea0282b4/networks/tunnels

- Remote Managment:
    - PVE1 iDRAC: 
        icon: /icons/catppuccin_icons/idrac.png
        href: https://10.42.91.100
    - PVE2 iDRAC: 
        icon: /icons/catppuccin_icons/idrac.png
        href: https://10.42.91.101
    - TrueNAS IPMI:
        icon: /icons/catppuccin_icons/supermicro.png
        href: http://10.42.91.125/

# Applications
- Development:
    - GitHub:
          icon: /icons/catppuccin_icons/github.png
          href: https://github.com/ColoredBytes
    - ChatGPT:
          icon: /icons/catppuccin_icons/chatgpt.png
          href: https://chatgpt.com

- Cockpit:
    - Docker:
        icon: /icons/catppuccin_icons/cockpit.png
        href: https://docker.int.jersh.tech:9090
    - DMZ Docker:
        icon: /icons/catppuccin_icons/cockpit.png
        href: https://dmz-docker.int.jersh.tech:9090
    - Plex:
        icon: /icons/catppuccin_icons/cockpit.png
        href: https://plex.int.jersh.tech:9090
    - LinuxGSM:
        icon: /icons/catppuccin_icons/cockpit.png
        href: https://game.int.jersh.tech:9090



# Entertainment
- Entertainment:
    - Plex:
        icon: /icons/catppuccin_icons/plex.png
        href: http://plex.int.jersh.tech:32400/web
        widget:
           type: plex
           url: http://plex.int.jersh.tech:32400
           key: ryHxFkPBAgyFq5d6ZTop
    - Tautulli:
        icon: /icons/catppuccin_icons/tatulli.png
        href: http://Tautulli.int.jersh.tech:8181/
        widget:
           type: tautulli
           url: http://Tautulli.int.jersh.tech:8181
           key: 631ef2e5f8914e85abd99420dc9c4be3

    
# Media Apps
- Media Management:
    - qFlood:
        icon: /icons/catppuccin_icons/flood.png
        href: http://qflood.int.jersh.tech:3000
    - qBittorrent:
        icon: /icons/catppuccin_icons/qbittorrent.png
        href: http://qbittorrent.int.jersh.tech:9080/
    - Prowlarr:
        icon: /icons/catppuccin_icons/prowlarr.png
        href: http://prowlarr.int.jersh.tech:9696
    - Overseerr:
        icon: /icons/catppuccin_icons/overseerr.png
        href: http://overseerr.int.jersh.tech:5055
    - Radarr:
        icon: /icons/catppuccin_icons/radarr.png
        href: http://radarr.int.jersh.tech:7878/
    - Sonarr:
        icon: /icons/catppuccin_icons/sonarr.png
        href: http://sonarr.int.jersh.tech:8989/
    - Anime Radarr:
        icon: /icons/catppuccin_icons/radarr.png
        href: http://anime-radarr.int.jersh.tech:6878/
    - Anime Sonarr:
        icon: /icons/catppuccin_icons/sonarr.png
        href: http://anime-sonarr.int.jersh.tech:7989/

# Services

- Admin :
    - Semaphore:
          icon: /icons/catppuccin_icons/semaphore.png
          href: https://semaphore.int.jersh.tech/auth/login
    - Home Assistant: 
          icon: /icons/catppuccin_icons/homeassistant.png
          href: http://homeassistant.int.jersh.tech:8123
    - Portainer  :
          icon: /icons/catppuccin_icons/portainer.png
          href: https://docker.int.jersh.tech:9443/
    - Zabbix:
          icon: /icons/catppuccin_icons/zabbix.png
          href: http://zabbix.int.jersh.tech/
    - Graylog:
          icon: /icons/catppuccin_icons/graylog.png
          href: http://graylog.int.jersh.tech
    - Grafana:
          icon: /icons/catppuccin_icons/grafana.png
          href: http://grafana.int.jersh.tech:3000
    - InfluxDB:
          icon: /icons/catppuccin_icons/influxdb.png
          href: http://influx.int.jersh.tech:8086
    - FreshRSS:
          icon: /icons/catppuccin_icons/freshrss.png
          href: http://rss.int.jersh.tech:8132
    - Dozzle:
          icon: /icons/catppuccin_icons/dozzle.png
          href: http://dozzle.int.jersh.tech:9999
    - Uptime-Kuma Dashboard :
          icon: /icons/catppuccin_icons/uptime-kuma.png
          href: https://status.jersh.tech/dashboard
    



   

    
    






