---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/settings

### DESIGN ###
color: gray
background:
  image: https://raw.githubusercontent.com/aynp/dracula-wallpapers/main/Programming%20Languages/4k/Helpful%20Comment.png
  blur: sm
title: Homepage  
favicon: /icons/custom/bookmark.ico
iconStyle: theme
headerStyle: underlined
hideVersion: true
target: _blank
showStats: false
statusStyle: "dot"

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey

### LAYTOUT ###
layout:
  Infrastructure :
    style: row
    columns: 2
    tab: Infrastructure
    icon: mdi-server
  Networking:
    style: column
    columns: 4
    tab: Infrastructure
    icon: mdi-network-outline
  Remote Managment:
    style: column
    columns: 3
    tab: Infrastructure
    icon: mdi-server-outline
  Development:
    style: row
    columns: 2
    tab: Applications
    icon: mdi-console
  Admin :
    style: row
    columns: 5
    tab: Applications
    icon: mdi-apps
  Cockpit:
    style: row
    columns: 4
    tab: Applications
    icon: mdi-server-outline
  Entertainment:
    style: row
    columns: 2
    tab: Media
    icon: mdi-plex
  Media Management:
    style: row
    columns: 5
    tab: Media
    icon: mdi-filmstrip
  Productivity:
    tab: Bookmarks
    style: column
    columns: 4
  Hosting:
    tab: Bookmarks
    style: column
    columns: 3
  Media:
    tab: Bookmarks
    style: column
    columns: 2
  Proxmox Tools:
    tab: Bookmarks
    style: column
    columns: 1
  Configuration:
    tab: Bookmarks
    style: column
    
 
  

    

   


  
    
  





  
    



