version: "3.1"
services:
  peppermint:
    container_name: peppermint
    hostname: peppermint
    image: pepperlabs/peppermint:latest
    ports:
      - 4000:3000
      - 5003:5003
    restart: always
    healthcheck:
      test:
        - CMD
        - sh
        - -c
        - wget --spider $$BASE_URL
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      DB_USERNAME: peppermint
      DB_PASSWORD: "1234"
      DB_HOST: 172.22.0.2
      SECRET: peppermint4life
      API_URL: http://0.0.0.0:5003
