- hosts: all
  gather_facts: yes
  become: true
  tasks:
    - name: Perform a dist-upgrade.
      ansible.builtin.apt:
        upgrade: dist
        update_cache: yes
    - name: Check if a reboot is required.
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required_file
    
