---
- hosts: all
  gather_facts: yes
  become: true
  tasks:
    - name: Update all packages
      dnf:
        name: "*"
        state: latest
    - name: Autoremove unnecessary packages
      dnf:
        autoremove: yes
    - name: Check if a reboot is required
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required_file
    
