---
services:
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /opt/docker/sabnzbd/config:/config
      - downloads:/mnt/media/downloads #optional
      - downloads:/mnt/media/incomplete-downloads #optional
    ports:
      - 8080:8080
    networks:
      arrstack:
        ipv4_address: 172.20.0.55
    restart: unless-stopped
  
volumes:
  shows:
    external: true
  movies:
    external: true
  downloads:
    external: true
  anime-movies:
    external: true
  anime:
    external: true
networks:
  arrstack:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
