version: "3.9"
services:
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    environment:
      - TZ=America/Detroit
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_SCHEDULE=0 3 * * *
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
  
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 9999:8080
    networks:
      - utility
    restart: unless-stopped

  uptime-kuma:
    image: 'louislam/uptime-kuma:1'
    container_name: uptime-kuma
    hostname: uptime-kuma
    volumes:
      - 'uptime-kuma:/app/data'
    ports:
      - '3001:3001'
    networks:
      - utility
    restart: unless-stopped

volumes:
  uptime-kuma:

networks:
  utility: {}
