version: "3.3"
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    hostname: homepage
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - 80:3000
    volumes:
      - homepage-config:/app/config # Shared volume for homepage config
      - homepage-config-images:/app/public/images # Separate volume for images
      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations
    restart: unless-stopped  
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    hostname: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Detroit
      - DEFAULT_WORKSPACE=/app/homepage # Set to homepage config directory
    volumes:
      - code-server-config:/config
      - homepage-config:/app/homepage # Same shared volume for homepage config
    ports:
      - 8443:8443
    restart: unless-stopped
volumes:
  homepage-config:
  homepage-config-images:
  code-server-config:
