version: "3.3"
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    hostname: homepage
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - 3000:3000
    volumes:
      - homepage-config:/app/config
      - /opt/docker/homepage/icons:/app/public/images
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    networks:
      - homepage-network
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    hostname: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Detroit
      - DEFAULT_WORKSPACE=/app/homepage
    volumes:
      - code-server-config:/config
      - homepage-config:/app/homepage
      - /opt/docker/homepage/icons:/app/homepage/images
    ports:
      - 8443:8443
    restart: unless-stopped
    networks:
      - homepage-network
volumes:
  homepage-config:
    external:
      true
  homepage-config-images:
    external:
      true
  code-server-config:
    external:
      true
networks:
  homepage-network:
