version: "3.9"
services:
  playit-docker:
    container_name: playit-docker
    hostname: playit-docker
    image: pepaondrugs/playitgg-docker:latest
    volumes:
        - playit-volume:/app
    networks:
      - proxy
    restart: unless-stopped
  
  cloudflared:
    image: cloudflare/cloudflared
    container_name: cloudflare-tunnel
    hostname: cloudflare-tunnel
    command: 'tunnel --no-autoupdate run --token '
    networks:
      - proxy
    restart: unless-stopped

   
    
volumes:
    playit-volume:
        external: false
networks:
  proxy: {}
