---
version: "3.3"
services:
  mariadb:
    image: mariadb:latest
    restart: unless-stopped
    ports:
      - 3306:3306
    networks:
      - mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=123456