services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    hostname: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /opt/docker/stacks/config/prowlarr:/config
    ports:
      - 9696:9696
    networks:
      - arrstack
    restart: unless-stopped
  overseerr:
    image: linuxserver/overseerr:1.33.2
    container_name: overseerr
    hostname: overseerr
    environment:
      - TZ=America/Detroit
      - PUID=1000
      - PGID=1000
    volumes:
      - /opt/docker/stacks/config/overseerr:/config
    ports:
      - 5055:5055/tcp
    networks:
      - arrstack
    restart: unless-stopped
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    hostname: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /opt/docker/stacks/config/radarr:/config
      - movies:/mnt/nas/movies
      - downloads:/app/qBittorrent/downloads
    ports:
      - 7878:7878
    networks:
      - arrstack
    restart: unless-stopped
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    hostname: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /opt/docker/stacks/config/sonarr:/config
      - shows:/mnt/nas/shows
      - downloads:/app/qBittorrent/downloads
    ports:
      - 8989:8989
    networks:
      - arrstack
    restart: unless-stopped
  radarr-anime:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr-anime
    hostname: radarr-anime
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /opt/docker/stacks/config/radarr-anime:/config
      - anime-movies:/mnt/nas/anime-movies
      - downloads:/app/qBittorrent/downloads
    ports:
      - 6878:6878
    networks:
      - arrstack
    restart: unless-stopped
  sonarr-anime:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr-anime
    hostname: sonarr-anime
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /opt/docker/stacks/config/sonarr-anime:/config
      - anime:/mnt/nas/anime
      - downloads:/app/qBittorrent/downloads
    ports:
      - 7989:7989
    networks:
      - arrstack
    restart: unless-stopped
  unpackerr:
    image: ghcr.io/hotio/unpackerr
    container_name: unpackerr
    hostname: unpackerr
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Etc/UTC
      - UN_SONARR_0_URL=
      - UN_SONARR_0_API_KEY=
      - UN_SONARR_1_URL=
      - UN_SONARR_1_API_KEY=
      - UN_RADARR_0_URL=
      - UN_RADARR_0_API_KEY=
      - UN_RADARR_1_URL=
      - UN_RADARR_1_API_KEY=
    volumes:
      - /opt/docker/stacks/config/unpackerr:/config
      - downloads:/app/qBittorrent/downloads
    restart: unless-stopped
  tautulli:
    image: ghcr.io/tautulli/tautulli
    container_name: tautulli
    hostname: tautulli
    volumes:
      - /opt/docker/stacks/config/tautulli:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Detroit
    ports:
      - 8181:8181
    networks:
      - arrstack
    restart: unless-stopped
volumes:
  shows:
    external: true
  movies:
    external: true
  downloads:
    external: true
  anime-movies:
    external: true
  anime:
    external: true
networks:
  arrstack: null
