version: "3"
services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana_container
    restart: unless-stopped
    ports:
      - 3000:3000
    networks:
      - monitoring-network
    volumes:
      - grafana-volume:/var/lib/grafana
  influxdb:
    image: influxdb:latest
    container_name: influxdb_container
    restart: unless-stopped
    ports:
      - 8086:8086
      - 8089:8089/udp
    networks:
      - monitoring-network
    volumes:
      - influxdb-volume:/var/lib/influxdb
networks:
  monitoring-network:
volumes:
  grafana-volume:
    external: true
  influxdb-volume:
    external: true